config/routes.rb
Rails.application.routes.draw do
  resources :games 

end

app/models/game.rb
class Game < ActiveRecord::Base
  def getResult
    return self.game_result
  end

  def newGame(myChoice)
    computerChoice = ''
    myToss = if rand(3) == 1 then
      computerChoice = 'rock'
    elsif myToss == 2
      computerChoice = 'paper'
    else
      computerChoice = 'scissors'
    end
    puts 'mychoice:' + myChoice
    puts 'computerChoice:' + computerChoice
    self.game_result = compare(myChoice,computerChoice)
    puts 'gameresult:' + self.game_result
    return self.game_result
  end

  def compare(myChoice,computerChoice)
    if myChoice == 'rock' && computerChoice == 'paper' then
      return 'lose'
    end
    if myChoice == 'rock' && computerChoice == 'rock' then
      return 'tie'
    end
    if myChoice == 'rock' && computerChoice == 'scissors' then
      return 'win'
    end

    if myChoice == 'paper' && computerChoice == 'paper' then
      return 'tie'
    end
    if myChoice == 'paper' && computerChoice == 'rock' then
      return 'lose'
    end
    if myChoice == 'paper' && computerChoice == 'scissors' then
      return 'win'
    end

    if myChoice == 'scissors' && computerChoice == 'paper' then
      return 'win'
    end
    if myChoice == 'scissors' && computerChoice == 'rock' then
      return 'lose'
    end
    if myChoice == 'scissors' && computerChoice == 'scissors' then
      return 'tie'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    puts 'games#index'
    @games = Game.all
  end

  def show
    puts 'games#show'
    puts '@game'
    puts @game
    puts '@game.getResult'
    puts @game.getResult
  end

  def create
    puts 'games#create'
    # @game = Game.new(game_params)
    puts '@game.getResult'
    puts @game.getResult
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
    puts 'end of create method'
  end

  def new
    puts 'games#new'
    @game = Game.new(params[:game])
    puts 'myChoice='
    puts params[:myChoice]
    if params[:myChoice] != nil then
      result = @game.newGame(params[:myChoice])
    end
    puts 'result'
    puts result
    puts '@game.getResult'
    puts @game.getResult
    create
  end

  def edit
    puts 'games#edit'
  end

  def update
    puts 'games#update'
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    puts 'games#destroy'
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.fetch(:game, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def total_wins(games)
    num_games_won = 0
    @games.each do |game|
      gameResult = game.game_result
      puts gameResult
      if (gameResult == 'win') then
        num_games_won += 1
      end
    end
    return num_games_won.to_s
  end

  def total_lost(games)
    num_games_lost = 0
    @games.each do |game|
      gameResult = game.game_result
      puts gameResult
      if (gameResult == 'lose') then
        num_games_lost += 1
      end
    end
    return num_games_lost.to_s
  end
   
  def total_tied(games)
    num_games_tied = 0
    @games.each do |game|
      gameResult = game.game_result
      puts gameResult
      if (gameResult == 'tie') then
        num_games_tied += 1
      end
    end
    return num_games_tied.to_s
  end

  def total_games(games)
    num_games_played = 0
    @games.each do |game|
      num_games_played += 1
    end
    return num_games_played.to_s
  end

  def total_unknown(games)
    num_games_unknown = 0
    @games.each do |game|
      gameResult = game.game_result
      puts gameResult
      if (gameResult == nil) then
        num_games_unknown += 1
      end
    end
    return num_games_unknown.to_s
  end

end

app/views/games/edit.html.erb
edit.html.erb

app/views/games/index.html.erb
index.html.erb

<h1>Welome to Rock Paper Scissors</h1>
<%= link_to 'Play Rock', new_game_path(myChoice: 'rock') %>
<%= link_to 'Play Paper', new_game_path(myChoice: 'paper') %>
<%= link_to 'Play Scissors', new_game_path(myChoice: 'scissors') %>
<table border=".5">
  <thead>
    <tr>
      <!-- <th colspan="3"></th> -->
      <th>Game</th>
      <th>Result</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
<!--     <tr>
      <td>Game ID</td>
      <td>Game Result</td>
      <td>Actions</td>
      <td></td>
    </tr> -->

    <% @games.each do |game| %>
      <tr>
        <td><%= game.id %></td>
        <td><%= game.game_result %></td>
        <!-- <td><%= link_to 'Show Game Result', game %></td> -->
        <td><%= link_to 'Delete Game', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h1>Games Played: <%= total_games(@games) %></h1>
<h1>Games Won: <%= total_wins(@games) %></h1>
<h1>Games Lost: <%= total_lost(@games) %></h1>
<h1>Games Tied: <%= total_tied(@games) %></h1>
<h1>Games Unknown: <%= total_unknown(@games) %></h1>

app/views/games/new.html.erb
new.html.erb

app/views/games/show.html.erb
show.html.erb
<h1>Welome to Rock Paper Scissors</h1>
<h3>Result:<%= @game.getResult %></h3>
<%= link_to 'Play Again', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>